import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { ScenarioTemplate, GEMINI_TEXT_MODEL } from "@reptrainer/shared";
import { getUserMetrics } from "@/lib/db";

// Initialize the Google Gen AI SDK
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY,
});

/**
 * Extracts JSON from a potentially markdown-wrapped AI response.
 */
function extractJson(text: string): string | null {
  const match = text.match(/\{[\s\S]*\}/);
  return match ? match[0] : null;
}

export async function POST(req: Request) {
  try {
    const { userId } = await req.json();

    if (!userId) {
      return NextResponse.json(
        { error: "userId is required" },
        { status: 400 },
      );
    }

    const metrics = await getUserMetrics(userId);
    let overallScore = 0;
    let strengths: string[] = [];
    let weaknesses: string[] = ["General sales skills (No prior data)"]; // Default

    if (metrics && metrics.totalCalls > 0) {
      overallScore = Math.round(metrics.averageScore);
      const skillScores = [
        { name: "Objection Handling", score: metrics.objectionHandlingAverage },
        { name: "Closing", score: metrics.closingSuccessAverage },
        { name: "Confidence", score: metrics.confidenceAverage },
      ].sort((a, b) => b.score - a.score); // Highest first

      strengths = [skillScores[0].name];
      weaknesses = [
        skillScores[skillScores.length - 1].name,
        skillScores[skillScores.length - 2].name,
      ];
    }

    const prompt = `You are an expert sales trainer AI.
Your goal is to generate a custom training scenario for a sales rep based on their recent performance.
The rep has an overall score of ${overallScore}/10.
Their strengths are: ${strengths.length > 0 ? strengths.join(", ") : "Unknown"}.
Their weaknesses are: ${weaknesses.join(", ")}.

Create a new, highly specific roleplay scenario that forces the rep to practice their weaknesses while leveraging their strengths contextually.
Return a valid JSON object matching this schema. Return ONLY JSON, no markdown formatting outside the JSON:
{
  "id": "adaptive-generated",
  "name": "string (Scenario Name)",
  "description": "string (A 2-3 sentence description of the scenario providing context)",
  "prospectPersonaType": "string (e.g., tough-negotiator, skeptical-buyer, budget-focused)",
  "difficulty": <number 1, 2, or 3>,
  "expectedSkills": ["string", "string", "string"],
  "evaluationWeighting": {
    "objection_handling": <number>,
    "closing_effectiveness": <number>,
    "confidence": <number>,
    "rapport_building": <number>,
    "discovery_skills": <number>
  },
  "systemPromptOverride": "string (The detailed instructions for the AI persona during the roleplay to target the weaknesses. e.g., 'You are a highly analytical buyer. Push back on ROI claims. If they fail to provide data, end the meeting.')"
}
Make sure evaluationWeighting values sum up to 100. Be extremely specific in the systemPromptOverride to challenge the weaknesses provided.
`;

    const response = await ai.models.generateContent({
      model: GEMINI_TEXT_MODEL || "gemini-1.5-pro",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const text = response.text;
    if (!text) {
      throw new Error("No text generated by Gemini");
    }

    const jsonStr = extractJson(text);
    if (!jsonStr) {
      throw new Error("Failed to extract JSON from response");
    }

    const scenario: ScenarioTemplate = JSON.parse(jsonStr);
    return NextResponse.json(scenario);
  } catch (error) {
    console.error("Error generating adaptive scenario:", error);
    return NextResponse.json(
      { error: "Failed to generate adaptive scenario" },
      { status: 500 },
    );
  }
}
